//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class XWorm_Main {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal XWorm_Main() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XWorm.Main", typeof(XWorm_Main).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ActiveWindowsToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ActiveWindowsToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap BlankScreenToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("BlankScreenToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap BotkillerToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("BotkillerToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ChromiumToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("ChromiumToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ChromiumToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ChromiumToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ClientChatToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("ClientChatToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ClientFolderToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("ClientFolderToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ClientToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ClientToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ClipboardManagerToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ClipboardManagerToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap CloseToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("CloseToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap CmstpToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("CmstpToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap CommandsToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("CommandsToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DDosAttackToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("DDosAttackToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DecryptToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("DecryptToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DeleteRestoreToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("DeleteRestoreToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DisableToolStripMenuItem10_Image {
        get {
            object obj = ResourceManager.GetObject("DisableToolStripMenuItem10.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DisableToolStripMenuItem11_Image {
        get {
            object obj = ResourceManager.GetObject("DisableToolStripMenuItem11.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DisableToolStripMenuItem6_Image {
        get {
            object obj = ResourceManager.GetObject("DisableToolStripMenuItem6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DisableToolStripMenuItem7_Image {
        get {
            object obj = ResourceManager.GetObject("DisableToolStripMenuItem7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DisableToolStripMenuItem8_Image {
        get {
            object obj = ResourceManager.GetObject("DisableToolStripMenuItem8.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DisableToolStripMenuItem9_Image {
        get {
            object obj = ResourceManager.GetObject("DisableToolStripMenuItem9.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DiscordTokenToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("DiscordTokenToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DiscordTokenToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("DiscordTokenToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DiskToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("DiskToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EditHostsToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("EditHostsToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EnableToolStripMenuItem10_Image {
        get {
            object obj = ResourceManager.GetObject("EnableToolStripMenuItem10.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EnableToolStripMenuItem11_Image {
        get {
            object obj = ResourceManager.GetObject("EnableToolStripMenuItem11.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EnableToolStripMenuItem6_Image {
        get {
            object obj = ResourceManager.GetObject("EnableToolStripMenuItem6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EnableToolStripMenuItem7_Image {
        get {
            object obj = ResourceManager.GetObject("EnableToolStripMenuItem7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EnableToolStripMenuItem8_Image {
        get {
            object obj = ResourceManager.GetObject("EnableToolStripMenuItem8.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EnableToolStripMenuItem9_Image {
        get {
            object obj = ResourceManager.GetObject("EnableToolStripMenuItem9.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap EncryptToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("EncryptToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ExitToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("ExitToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Extra1ToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("Extra1ToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Extra2ToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("Extra2ToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FileManagerToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("FileManagerToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FilesSearcherToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("FilesSearcherToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FileZillaToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("FileZillaToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FirewallToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("FirewallToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FodhelperToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("FodhelperToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FromDiskToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("FromDiskToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FromLinkToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("FromLinkToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap FromMemoryToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("FromMemoryToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2Button1_Image {
        get {
            object obj = ResourceManager.GetObject("Guna2Button1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2Button2_Image {
        get {
            object obj = ResourceManager.GetObject("Guna2Button2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2Button3_Image {
        get {
            object obj = ResourceManager.GetObject("Guna2Button3.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2Button4_Image {
        get {
            object obj = ResourceManager.GetObject("Guna2Button4.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2Button5_Image {
        get {
            object obj = ResourceManager.GetObject("Guna2Button5.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2Button6_Image {
        get {
            object obj = ResourceManager.GetObject("Guna2Button6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2Button7_Image {
        get {
            object obj = ResourceManager.GetObject("Guna2Button7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Guna2TextBox1_IconLeft {
        get {
            object obj = ResourceManager.GetObject("Guna2TextBox1.IconLeft", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap HiddenAppsToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("HiddenAppsToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap HiddenBrowserToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("HiddenBrowserToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap HiddenRDPToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("HiddenRDPToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap HiddenVNCToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("HiddenVNCToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Windows.Forms.ImageListStreamer.
    /// </summary>
    internal static System.Windows.Forms.ImageListStreamer ii_ImageStream {
        get {
            object obj = ResourceManager.GetObject("ii.ImageStream", resourceCulture);
            return ((System.Windows.Forms.ImageListStreamer)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap InformationToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("InformationToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap InstalledProgramsToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("InstalledProgramsToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap InvisibleToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("InvisibleToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap InvisibleToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("InvisibleToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap InvokeBSODToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("InvokeBSODToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap KeyloggerToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("KeyloggerToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap KeyLoggerToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("KeyLoggerToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap LinkToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("LinkToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap LocationManagerToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("LocationManagerToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap LogoffToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("LogoffToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MemoryToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("MemoryToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MemoryToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("MemoryToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MessageBoxToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("MessageBoxToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MetaMaskToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("MetaMaskToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MetaMaskToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("MetaMaskToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MicrophoneToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("MicrophoneToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap MonitorToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("MonitorToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Net35InstallToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("Net35InstallToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NgrokInstallerToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("NgrokInstallerToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap NoteToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("NoteToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    /// </summary>
    internal static System.Drawing.Icon NotifyIcon1_Icon {
        get {
            object obj = ResourceManager.GetObject("NotifyIcon1.Icon", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap OfflineToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("OfflineToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap OnlineToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("OnlineToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap OpenUrlToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("OpenUrlToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap OpenUrlToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("OpenUrlToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap OptionsToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("OptionsToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap PastimeToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("PastimeToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap PerformanceToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("PerformanceToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap PowerToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("PowerToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ProcessManagerToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ProcessManagerToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ProductKeyToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ProductKeyToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RansomwareToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RansomwareToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RecoveryOptionsToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("RecoveryOptionsToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RecoveryToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RecoveryToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RegeditToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RegeditToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RegistryEditorToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RegistryEditorToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RemoveTaskToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RemoveTaskToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ReportWindowToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ReportWindowToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ResetScaleToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ResetScaleToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RestartToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("RestartToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RestartToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RestartToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RestartToolStripMenuItem4_Image {
        get {
            object obj = ResourceManager.GetObject("RestartToolStripMenuItem4.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ReverseProxyToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ReverseProxyToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RunAsToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RunAsToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RunFileToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("RunFileToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RunPEToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("RunPEToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RunPEToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("RunPEToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RunRecoveryToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("RunRecoveryToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap RunRecoveryToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("RunRecoveryToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ServiceManagerToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("ServiceManagerToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ShellToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("ShellToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ShowToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("ShowToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ShutdownToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("ShutdownToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap StartToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("StartToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap StartupManagerToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("StartupManagerToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap StopToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("StopToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap SystemSoundToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("SystemSoundToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TaskMgrToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("TaskMgrToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TCPConnectionsToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("TCPConnectionsToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TelegramSessionToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("TelegramSessionToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap TelegramSessionToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("TelegramSessionToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ToolStripMenuItem4_Image {
        get {
            object obj = ResourceManager.GetObject("ToolStripMenuItem4.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ToolStripMenuItem6_Image {
        get {
            object obj = ResourceManager.GetObject("ToolStripMenuItem6.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ToolStripMenuItem7_Image {
        get {
            object obj = ResourceManager.GetObject("ToolStripMenuItem7.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap UACBypassToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("UACBypassToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap UACToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("UACToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap UninstallPluginsToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("UninstallPluginsToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap UninstallToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("UninstallToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap UpdateAllClientsToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("UpdateAllClientsToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap UpdateToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("UpdateToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap UpdateToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("UpdateToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap VBNetCompilerToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("VBNetCompilerToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap VisibleToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("VisibleToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap VisibleToolStripMenuItem2_Image {
        get {
            object obj = ResourceManager.GetObject("VisibleToolStripMenuItem2.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap VoiceChatToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("VoiceChatToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap WDDisableToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("WDDisableToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap WDExclusionToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("WDExclusionToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap WDExclusionToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("WDExclusionToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap WDKillerToolStripMenuItem_Image {
        get {
            object obj = ResourceManager.GetObject("WDKillerToolStripMenuItem.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap WebCamToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("WebCamToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap WifiKeysToolStripMenuItem1_Image {
        get {
            object obj = ResourceManager.GetObject("WifiKeysToolStripMenuItem1.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
